//! 0.57.0: the notes a turn is handed are the notes that turn needs.
//!
//! Through 0.56.0 the memory block kept the newest notes that fit, which is the
//! right answer only while the whole store fits its quarter-share of the turn —
//! and 0.56.0 is the release that let an operator raise the caps past that
//! point. Here the notes that survive the fit are chosen by what the turn is
//! about: the words of its goal, the paths it has already read, then how many
//! separate runs have carried the entry, then the write clock.
//!
//! **What is printed is not what is chosen.** The block is always rendered in
//! the store's own order, so a store that fits its share renders byte-identically
//! however the turn moves — which is what keeps 0.44.0's cache boundary. The two
//! orders being different is the whole shape of this release, and F5 is the test
//! that fails if an implementation collapses them into one.

use std::path::Path;

use io_harness::provider::{CompletionRequest, CompletionResponse, ToolCall};
use io_harness::{
    run_with, ApproveAll, ContextBudget, MemoryKind, MemoryLimits, Policy, Provider, Store,
    TaskContract,
};
use serde_json::json;

/// Every prompt the model was sent, so an assertion can be made about what the
/// block actually said rather than about what the store holds.
struct Seen(std::sync::Mutex<Vec<String>>, Vec<Vec<ToolCall>>);

impl Provider for Seen {
    async fn complete(&self, req: CompletionRequest) -> io_harness::Result<CompletionResponse> {
        // A fold's summarisation request carries no tools and must be answered with
        // prose: a summariser that says nothing is not allowed to replace the notes
        // with nothing, so an empty answer aborts the fold and a fixture written to
        // fold silently never does. It takes no slot in the script either — the
        // script is the agent's turns, and this is not one of them. It is not
        // recorded either: the script is indexed by how many prompts have been
        // seen, so recording it would slide every later step onto the wrong turn.
        // (0.85.0) Recognised by the instruction rather than by an empty tool list:
        // the fold now extends the step's own request, tools and all.
        if req.user.contains("compacting an agent's own working notes") {
            return Ok(CompletionResponse {
                text: Some("the run read a few files".into()),
                ..Default::default()
            });
        }
        let mut seen = self.0.lock().unwrap();
        let i = seen.len();
        seen.push(req.user.clone());
        Ok(CompletionResponse {
            tool_calls: self.1.get(i).cloned().unwrap_or_default(),
            ..Default::default()
        })
    }
    fn name(&self) -> &str {
        "seen"
    }
}

fn ws_key(root: &Path) -> String {
    std::fs::canonicalize(root)
        .unwrap_or_else(|_| root.to_path_buf())
        .to_string_lossy()
        .into_owned()
}

/// A ceiling that cannot hold every note, which is the only regime in which
/// selection is observable at all.
fn contract(root: &Path, goal: &str) -> TaskContract {
    TaskContract::workspace(goal, root)
        .with_max_steps(3)
        .with_context_budget(ContextBudget {
            max_tokens: 1_000,
            share: 0.5,
        })
}

/// Run `steps` tool calls over `root` and return every prompt the model saw.
async fn prompts(root: &Path, store: &Store, goal: &str, steps: Vec<Vec<ToolCall>>) -> Vec<String> {
    let seen = Seen(std::sync::Mutex::new(Vec::new()), steps);
    run_with(
        &contract(root, goal),
        &seen,
        store,
        &Policy::permissive(),
        &ApproveAll,
    )
    .await
    .expect("the run itself must not error");
    let out = seen.0.lock().unwrap().clone();
    out
}

/// Nine notes on three subjects, written oldest subject first, with opaque keys
/// so an assertion about a key is never accidentally satisfied by the goal.
///
/// The three vocabularies are disjoint on purpose: a token shared between two
/// subjects would make the test's own premise — that only one subject matches —
/// something the reader has to verify by eye.
fn three_subjects(store: &Store, key: &str) {
    let notes: [(&str, &str); 9] = [
        (
            "n01",
            "the parser rejects a trailing comma and reports the column it stopped at",
        ),
        (
            "n02",
            "parser fixtures live beside the grammar and are regenerated by hand",
        ),
        (
            "n03",
            "a parser failure is reported with the token, never with the byte offset",
        ),
        (
            "n04",
            "the sandbox refuses an absent writable root rather than degrading quietly",
        ),
        (
            "n05",
            "sandbox setup binds every root it is given before it enters the directory",
        ),
        (
            "n06",
            "a contained spawn resolves the program against PATH before it starts",
        ),
        (
            "n07",
            "the release tag is pushed alone or the workflow ships with no assets",
        ),
        (
            "n08",
            "release notes are taken verbatim from the changelog by the workflow",
        ),
        (
            "n09",
            "publishing happens last, after both merges and after the tag exists",
        ),
    ];
    for (i, (k, v)) in notes.iter().enumerate() {
        // Padded, so nine notes cannot fit the block's share and something has
        // to be chosen. The padding is one token and shares nothing with any
        // goal, so it changes the arithmetic without changing the ranking.
        let value = format!("{v} {}", "z".repeat(240));
        store
            .memory_put(key, k, &value, 1, 1 + i as u32)
            .expect("the fixture writes must land");
    }
}

/// F1 — a turn about one subject is handed the notes about that subject, and the
/// notes it is not about are the ones elided.
///
/// The control is written out rather than described: the release notes are the
/// three newest in the store, so under 0.56.0's ordering they are exactly the
/// ones that survive. The test asserts they do not.
#[tokio::test]
async fn a_turn_about_one_subject_carries_the_notes_about_that_subject() {
    let dir = tempfile::tempdir().unwrap();
    let store = Store::memory().unwrap();
    let key = ws_key(dir.path());
    three_subjects(&store, &key);

    // The control, asserted rather than assumed: n07..n09 are the newest three,
    // so 0.56.0 would have kept them and dropped the parser notes.
    let listed = store.memory_list(&key).unwrap();
    let newest: Vec<&str> = listed
        .iter()
        .rev()
        .take(3)
        .map(|e| e.key.as_str())
        .collect();
    assert_eq!(
        newest,
        vec!["n09", "n08", "n07"],
        "the fixture's premise: the release notes are the newest in the store"
    );

    let prompt = prompts(dir.path(), &store, "fix the parser", vec![vec![]])
        .await
        .remove(0);
    assert!(
        prompt.contains("note(s) elided to fit"),
        "the fixture must not fit, or nothing is being selected:\n{prompt}"
    );
    // Every note that survived is a parser note — asserted over what the block
    // rendered rather than by naming the ones expected to be there, because how
    // MANY fit is the ceiling's business and which SUBJECT fits is the release's.
    // Three notes tie on the signal here and the block holds fewer than three,
    // so an assertion listing all of them would be asserting the ceiling.
    let carried: Vec<String> = prompt
        .lines()
        .filter_map(|l| l.strip_prefix("- "))
        .filter_map(|l| l.split(':').next())
        .filter(|k| k.starts_with('n'))
        .map(str::to_string)
        .collect();
    assert!(
        !carried.is_empty(),
        "at least one note always survives:\n{prompt}"
    );
    for k in &carried {
        assert!(
            ["n01", "n02", "n03"].contains(&k.as_str()),
            "{k} is not a parser note and this turn is about the parser:\n{prompt}"
        );
    }
    for dropped in ["n07", "n08", "n09"] {
        assert!(
            !prompt.contains(&format!("- {dropped}:")),
            "{dropped} is the newest cohort and this turn is not about it — recency won:\n{prompt}"
        );
    }
}

/// F2 — a path the run has already read counts as a signal, and the block that
/// signal chooses is then held still for the rest of the run.
///
/// The goal deliberately names nothing in the store: with signals from the goal
/// alone the sandbox notes have no claim, and the newest cohort survives. It is
/// reading the file that moves them.
///
/// **(0.85.0) The ranking is taken once per run and again at each fold, not once
/// per step.** The block renders ahead of everything the run observes, so a block
/// that re-ranked mid-run rewrote the earliest bytes of the prompt on a step where
/// nothing else had changed — one cache miss per step, for a re-ordering the model
/// had already read. What the signal decides is unchanged; when it is asked is.
/// Across the turns of a session the signal still moves the block, because a turn's
/// ledger is seeded with the turns before it — that is
/// [`a_session_turn_recalls_by_what_the_turn_before_it_read`].
#[tokio::test]
async fn a_path_the_run_has_read_is_a_signal_the_next_turn_recalls_by() {
    let dir = tempfile::tempdir().unwrap();
    let store = Store::memory().unwrap();
    let key = ws_key(dir.path());
    three_subjects(&store, &key);
    std::fs::write(
        dir.path().join("sandbox.rs"),
        "// the file this run reads\n",
    )
    .unwrap();

    let read = ToolCall {
        name: "read_file".into(),
        arguments: json!({ "path": "sandbox.rs" }),
    };
    let seen = prompts(
        dir.path(),
        &store,
        "carry out the assignment",
        vec![vec![read], vec![]],
    )
    .await;
    assert_eq!(
        seen.len(),
        2,
        "two turns, so the ledger differs between them"
    );

    // Turn one: nothing has been read, the goal matches nothing, so the store's
    // own order decides and the newest cohort is carried.
    assert!(
        seen[0].contains("- n09:"),
        "with no signal at all the newest note is kept, as it was through 0.56.0:\n{}",
        seen[0]
    );
    // Step two: the block the run started with, byte for byte. The run has read
    // `sandbox.rs` by now and `sandbox` is a word three notes share, but the block
    // sits ahead of everything the run observes and re-ranking it here would move
    // the earliest bytes of the prompt on a step where nothing else had.
    assert_eq!(
        block(&seen[0]),
        block(&seen[1]),
        "the block is taken once per run and held; step two re-ranked it"
    );
}

/// The memory block of a prompt, which is what must stand still within a run.
fn block(prompt: &str) -> &str {
    let from = prompt.find("\n[memory]").expect("the prompt carries a block");
    let rest = &prompt[from..];
    let to = ["\n<external_content>", "\n\nCall a tool", "\n\n["]
        .iter()
        .filter_map(|mark| rest.find(mark))
        .min()
        .unwrap_or(rest.len());
    rest[..to].trim_end()
}

/// F2 (the fold half, 0.85.0) — the signal still moves the block, and a fold is
/// where it moves it.
///
/// The ranking is asked for again whenever the prefix is being rebuilt anyway, and
/// by then the run has read the file — so the sandbox notes take the block that the
/// newest cohort held at run start. This is the coverage the case above used to
/// carry at step granularity, at the granularity 0.85.0 moved it to. Without it,
/// "the signal still decides" would be a claim with nothing asserting it.
///
/// The signals are taken before the fold runs, which is what makes the read
/// countable: a fold folds the read away, and a ranking taken after it would see a
/// summary and no path at all.
#[tokio::test]
async fn a_fold_re_ranks_the_block_by_what_the_run_has_read() {
    let dir = tempfile::tempdir().unwrap();
    let store = Store::memory().unwrap();
    let key = ws_key(dir.path());
    three_subjects(&store, &key);
    std::fs::write(
        dir.path().join("sandbox.rs"),
        "// the file this run reads\n",
    )
    .unwrap();
    for i in 0..6 {
        std::fs::write(
            dir.path().join(format!("f{i}.txt")),
            format!("file {i}\n{}", "filler line\n".repeat(60)),
        )
        .unwrap();
    }

    let mut script = vec![vec![ToolCall {
        name: "read_file".into(),
        arguments: json!({ "path": "sandbox.rs" }),
    }]];
    script.extend((0..6).map(|i| {
        vec![ToolCall {
            name: "read_file".into(),
            arguments: json!({ "path": format!("f{i}.txt") }),
        }]
    }));
    let steps = script.len() as u32;
    let seen = Seen(std::sync::Mutex::new(Vec::new()), script);

    // The same 1,000-token ceiling the rest of this file ranks under: a block that
    // holds every note makes a ranking unobservable, which is what a wider one did
    // when this case was first written.
    let contract = TaskContract::workspace("carry out the assignment", dir.path())
        .with_max_steps(steps)
        .with_context_budget(ContextBudget {
            max_tokens: 1_000,
            share: 0.5,
        })
        .with_compaction(io_harness::Compaction {
            at_share: 0.8,
            keep_recent: 2,
        });
    run_with(
        &contract,
        &seen,
        &store,
        &Policy::permissive(),
        &ApproveAll,
    )
    .await
    .expect("the run itself must not error");

    let prompts = seen.0.lock().unwrap().clone();
    let first = prompts
        .iter()
        .find(|p| p.contains("\n[memory]"))
        .expect("the first step carried a block");
    // The first fold, and not the last prompt: a fold folds the read away, so by the
    // second fold the path is no longer among the signals and the ranking falls back
    // to recency. What is being asserted is that a fold asks again, and the first one
    // is where the answer is visibly different.
    let last = prompts
        .iter()
        .find(|p| p.contains("[earlier work, summarised]"))
        .expect("the fixture must fold, or there is no re-ranking to observe");
    // At run start nothing has been read, so the goal alone ranks and the sandbox
    // notes have no claim.
    assert!(
        !["n04", "n05"]
            .iter()
            .any(|kept| block(first).contains(&format!("- {kept}:"))),
        "the fixture's premise is that the sandbox notes start with no claim:\n{}",
        block(first)
    );
    // By the fold the run has read `sandbox.rs`, and `sandbox` is a word three
    // notes share.
    assert!(
        ["n04", "n05"]
            .iter()
            .all(|kept| block(last).contains(&format!("- {kept}:"))),
        "the run has read sandbox.rs and the fold is where that counts:\n{}",
        block(last)
    );
    assert_ne!(
        block(first),
        block(last),
        "a fold is where the ranking is asked for again; nothing moved"
    );
}

/// A ceiling that holds one note and not two, for the tie-break assertions —
/// where the whole claim is about which single entry survives.
fn tight(root: &Path, goal: &str) -> TaskContract {
    TaskContract::workspace(goal, root)
        .with_max_steps(2)
        .with_context_budget(ContextBudget {
            max_tokens: 600,
            share: 0.5,
        })
}

async fn tight_prompt(root: &Path, store: &Store, goal: &str) -> String {
    let seen = Seen(std::sync::Mutex::new(Vec::new()), vec![vec![]]);
    run_with(
        &tight(root, goal),
        &seen,
        store,
        &Policy::permissive(),
        &ApproveAll,
    )
    .await
    .expect("the run itself must not error");
    let out = seen.0.lock().unwrap().clone();
    out.into_iter().next().expect("one step happened")
}

/// F3 — draws break a signal tie, and the store's order breaks a draw tie.
///
/// The evidence is earned rather than inserted: `record_memory_recall` is the
/// crate's own, and a test that wrote its rows directly would be asserting
/// against a table no run had produced. Three runs happen while `s1` is the only
/// note in the store, so three runs carry it; `s2` is written afterwards, which
/// makes it both the newer entry and the one with nothing behind it. The clock
/// and the evidence therefore point opposite ways, which is the only arrangement
/// in which the assertion means anything.
#[tokio::test]
async fn draws_break_a_signal_tie_and_the_store_order_breaks_a_draw_tie() {
    let dir = tempfile::tempdir().unwrap();
    let store = Store::memory().unwrap();
    let key = ws_key(dir.path());

    // Both notes match a `sandbox` goal by exactly one word and share none of
    // their other vocabulary with it, so the first rank term cannot separate
    // them. Long enough that two of them cannot fit the tight ceiling.
    let s1 = format!(
        "sandbox setup binds every root it is given, {}",
        "x".repeat(200)
    );
    let s2 = format!(
        "sandbox refuses an absent writable root, {}",
        "y".repeat(200)
    );
    store.memory_put(&key, "s1", &s1, 1, 1).unwrap();
    for _ in 0..3 {
        tight_prompt(dir.path(), &store, "look at sandbox behaviour").await;
    }
    store.memory_put(&key, "s2", &s2, 1, 2).unwrap();

    let prompt = tight_prompt(dir.path(), &store, "look at sandbox behaviour").await;
    assert!(
        prompt.contains("- s1:"),
        "three runs have carried s1 and nothing has carried s2:\n{prompt}"
    );
    assert!(
        !prompt.contains("- s2:"),
        "s2 is newer, and being newer must not beat the evidence s1 earned:\n{prompt}"
    );

    // The tail: with no evidence anywhere and nothing in the goal to match, the
    // surviving entry is the store's own last one — 0.56.0's behaviour kept as
    // the tie-break rather than replaced.
    let quiet = Store::memory().unwrap();
    quiet.memory_put(&key, "s1", &s1, 1, 1).unwrap();
    quiet.memory_put(&key, "s2", &s2, 1, 2).unwrap();
    let prompt = tight_prompt(dir.path(), &quiet, "carry out the assignment").await;
    assert!(
        prompt.contains("- s2:") && !prompt.contains("- s1:"),
        "with nothing to rank by, the order the store returned decides:\n{prompt}"
    );
}

/// F5 — the printed block is the store's order, whatever the turn is about.
///
/// This is the caching claim, and it is asserted on bytes. Two runs over one
/// store with two goals that select **different** notes still print what they
/// kept in `(created_at, key)` order, and a store that fits its share prints
/// byte-identically under both goals — which is what makes the memory block a
/// repeatable prefix and 0.44.0's second cache breakpoint still reachable.
#[tokio::test]
async fn the_block_is_printed_in_the_stores_order_however_the_turn_moves() {
    let dir = tempfile::tempdir().unwrap();
    let store = Store::memory().unwrap();
    let key = ws_key(dir.path());
    three_subjects(&store, &key);

    let block = |prompt: &str| {
        let start = prompt.find("[memory]").expect("a block was rendered");
        let rest = &prompt[start..];
        let end = rest.find("\n\n").unwrap_or(rest.len());
        rest[..end].to_string()
    };
    let keys_in_order = |b: &str| {
        b.lines()
            .filter_map(|l| l.strip_prefix("- "))
            .filter_map(|l| l.split(':').next())
            .filter(|k| k.starts_with('n'))
            .map(str::to_string)
            .collect::<Vec<_>>()
    };

    let parser = block(&prompts(dir.path(), &store, "fix the parser", vec![vec![]]).await[0]);
    let release = block(&prompts(dir.path(), &store, "cut the release", vec![vec![]]).await[0]);
    assert_ne!(
        keys_in_order(&parser),
        keys_in_order(&release),
        "the two goals must select different notes, or this test proves nothing"
    );
    for b in [&parser, &release] {
        let printed = keys_in_order(b);
        let mut sorted = printed.clone();
        sorted.sort();
        assert_eq!(
            printed, sorted,
            "the block is printed in the store's order, never in the order the fit chose:\n{b}"
        );
    }

    // The half that carries the caching claim: when everything fits, the block
    // does not move at all between two turns about different things.
    let small = Store::memory().unwrap();
    small
        .memory_put(&key, "a01", "the parser rejects a trailing comma", 1, 1)
        .unwrap();
    small
        .memory_put(&key, "a02", "the release tag is pushed alone", 1, 2)
        .unwrap();
    let one = block(&prompts(dir.path(), &small, "fix the parser", vec![vec![]]).await[0]);
    let two = block(&prompts(dir.path(), &small, "cut the release", vec![vec![]]).await[0]);
    assert_eq!(
        one, two,
        "a store inside its share renders byte-identically whatever the turn is about"
    );
    assert!(
        !one.contains("elided to fit"),
        "the fixture for this half must fit, or it is asserting the other regime"
    );
}

/// F7 — the ranking reaches the sub-agent loop.
///
/// `run_tree_with_extras` is a second recall site, and a rule that lives in one
/// loop and not the other is this crate's most repeated defect shape. Asserted
/// by driving a real spawn and reading the **child's** own prompt — the child's
/// goal is about the parser and the parent's is about nothing in the store, so a
/// child falling back to recency is visible as the newest cohort appearing in a
/// block that should hold parser notes.
#[tokio::test]
async fn a_spawned_child_recalls_under_the_same_ordering_as_the_flat_loop() {
    use io_harness::{run_tree, AgentDef, Agents, Containment};

    let dir = tempfile::tempdir().unwrap();
    let store = Store::memory().unwrap();
    let key = ws_key(dir.path());
    // A child's `TaskContract` is built fresh by the spawn (`src/run.rs`) and does
    // NOT inherit the root's `ContextBudget`, so a child always assembles under
    // the default 24,000-token ceiling however tightly the root was bounded. The
    // fixture is sized against that ceiling rather than against the one the other
    // tests here set — and it has to be written through `memory_write_with`,
    // because a store this large is past the caps `memory_put` enforces.
    let big = MemoryLimits {
        max_entries: 1_000,
        max_chars: 10_000_000,
        max_entry_chars: 2_000,
    };
    let subjects = [
        (
            "a",
            "the parser rejects a trailing comma and reports the column it stopped at",
        ),
        (
            "b",
            "the sandbox refuses an absent writable root rather than degrading quietly",
        ),
        (
            "c",
            "the release tag is pushed alone or the workflow ships with no assets",
        ),
    ];
    for (s, text) in subjects {
        for i in 0..12 {
            let value = format!("{text} {}", "z".repeat(1_800));
            store
                .memory_write_with(
                    &key,
                    &format!("{s}{i:02}"),
                    &value,
                    1,
                    1,
                    MemoryKind::Fact,
                    big,
                )
                .expect("the fixture writes must land");
        }
    }

    let spawn = ToolCall {
        name: "spawn_agent".into(),
        arguments: json!({
            "agent": "reader",
            "goal": "fix the parser",
            "verify_file": "done.txt",
            "verify_contains": "ok",
            "max_steps": 2
        }),
    };
    let write = ToolCall {
        name: "write_file".into(),
        arguments: json!({ "path": "done.txt", "content": "ok" }),
    };

    let seen = Seen(
        std::sync::Mutex::new(Vec::new()),
        vec![vec![spawn], vec![write], vec![]],
    );
    let contract = TaskContract::workspace("delegate the assignment", dir.path())
        .with_max_steps(3)
        .with_context_budget(ContextBudget {
            max_tokens: 1_000,
            share: 0.5,
        })
        .with_agents(Agents::new().with(AgentDef::new("reader")));
    let _ = run_tree(
        &contract,
        &seen,
        &store,
        &Policy::permissive(),
        &ApproveAll,
        &Containment::new(4, 2, 2, 1_000_000),
    )
    .await;

    let prompts = seen.0.lock().unwrap().clone();
    let child = prompts
        .iter()
        .find(|p| p.contains("Goal: fix the parser"))
        .expect("the child ran and was prompted with its own goal");
    assert!(
        child.contains("note(s) elided to fit"),
        "the child's block must not fit, or nothing is being selected in the tree loop:\n{child}"
    );
    let carried: Vec<String> = child
        .lines()
        .filter_map(|l| l.strip_prefix("- "))
        .filter_map(|l| l.split(':').next())
        .filter(|k| k.len() == 3 && k.starts_with(['a', 'b', 'c']))
        .map(str::to_string)
        .collect();
    assert!(
        !carried.is_empty(),
        "the child recalled nothing at all, so this asserts nothing:\n{child}"
    );
    for k in &carried {
        assert!(
            k.starts_with('a'),
            "the child carried {k}, which is not about its own goal — the tree loop \
             is still recalling by recency"
        );
    }

    // And the parent, whose goal matches nothing, is the control: it carries the
    // store's own last notes, which is what a child would have carried too if the
    // ranking had not reached it.
    let parent = prompts
        .iter()
        .find(|p| p.contains("Goal: delegate the assignment"))
        .expect("the parent was prompted too");
    assert!(
        parent.contains("- c11:"),
        "the parent's goal matches nothing, so the store's own last entry decides for it"
    );
}

/// F6 — the same store and the same turn select the same notes twice.
///
/// The ordering is a pure function of the store and the turn, which is what lets
/// a replayed run recall what the run it replays did. Asserted by running the
/// same turn twice over one store and comparing the whole prompt, then by
/// writing one note and asserting the new selection is itself repeatable rather
/// than merely different.
#[tokio::test]
async fn the_same_store_and_the_same_turn_select_the_same_notes_twice() {
    let dir = tempfile::tempdir().unwrap();
    let store = Store::memory().unwrap();
    let key = ws_key(dir.path());
    three_subjects(&store, &key);

    let once = prompts(dir.path(), &store, "fix the parser", vec![vec![]]).await;
    let twice = prompts(dir.path(), &store, "fix the parser", vec![vec![]]).await;
    assert_eq!(
        once[0], twice[0],
        "two identical turns over one store must assemble one prompt"
    );

    store
        .memory_put(&key, "n10", "the parser keeps a token's own span", 1, 10)
        .unwrap();
    let after = prompts(dir.path(), &store, "fix the parser", vec![vec![]]).await;
    let again = prompts(dir.path(), &store, "fix the parser", vec![vec![]]).await;
    assert_ne!(
        once[0], after[0],
        "a note that matches the turn must change what is carried, or the first \
         assertion holds for the wrong reason"
    );
    assert_eq!(
        after[0], again[0],
        "the new selection is a function of the new store, not of anything else"
    );
}
