//! 0.57.0: the notes a turn is handed are the notes that turn needs.
//!
//! Through 0.56.0 the memory block kept the newest notes that fit, which is the
//! right answer only while the whole store fits its quarter-share of the turn —
//! and 0.56.0 is the release that let an operator raise the caps past that
//! point. Here the notes that survive the fit are chosen by what the turn is
//! about: the words of its goal, the paths it has already read, then how many
//! separate runs have carried the entry, then the write clock.
//!
//! **What is printed is not what is chosen.** The block is always rendered in
//! the store's own order, so a store that fits its share renders byte-identically
//! however the turn moves — which is what keeps 0.44.0's cache boundary. The two
//! orders being different is the whole shape of this release, and F5 is the test
//! that fails if an implementation collapses them into one.

use std::path::Path;

use io_harness::provider::{CompletionRequest, CompletionResponse, ToolCall};
use io_harness::{
    run_with, ApproveAll, ContextBudget, Policy, Provider, Store, TaskContract,
};
use serde_json::json;

/// Every prompt the model was sent, so an assertion can be made about what the
/// block actually said rather than about what the store holds.
struct Seen(std::sync::Mutex<Vec<String>>, Vec<Vec<ToolCall>>);

impl Provider for Seen {
    async fn complete(&self, req: CompletionRequest) -> io_harness::Result<CompletionResponse> {
        let mut seen = self.0.lock().unwrap();
        let i = seen.len();
        seen.push(req.user.clone());
        Ok(CompletionResponse {
            tool_calls: self.1.get(i).cloned().unwrap_or_default(),
            ..Default::default()
        })
    }
    fn name(&self) -> &str {
        "seen"
    }
}

fn ws_key(root: &Path) -> String {
    std::fs::canonicalize(root)
        .unwrap_or_else(|_| root.to_path_buf())
        .to_string_lossy()
        .into_owned()
}

/// A ceiling that cannot hold every note, which is the only regime in which
/// selection is observable at all.
fn contract(root: &Path, goal: &str) -> TaskContract {
    TaskContract::workspace(goal, root)
        .with_max_steps(3)
        .with_context_budget(ContextBudget {
            max_tokens: 1_000,
            share: 0.5,
        })
}

/// Run `steps` tool calls over `root` and return every prompt the model saw.
async fn prompts(root: &Path, store: &Store, goal: &str, steps: Vec<Vec<ToolCall>>) -> Vec<String> {
    let seen = Seen(std::sync::Mutex::new(Vec::new()), steps);
    run_with(
        &contract(root, goal),
        &seen,
        store,
        &Policy::permissive(),
        &ApproveAll,
    )
    .await
    .expect("the run itself must not error");
    let out = seen.0.lock().unwrap().clone();
    out
}

/// Nine notes on three subjects, written oldest subject first, with opaque keys
/// so an assertion about a key is never accidentally satisfied by the goal.
///
/// The three vocabularies are disjoint on purpose: a token shared between two
/// subjects would make the test's own premise — that only one subject matches —
/// something the reader has to verify by eye.
fn three_subjects(store: &Store, key: &str) {
    let notes: [(&str, &str); 9] = [
        ("n01", "the parser rejects a trailing comma and reports the column it stopped at"),
        ("n02", "parser fixtures live beside the grammar and are regenerated by hand"),
        ("n03", "a parser failure is reported with the token, never with the byte offset"),
        ("n04", "the sandbox refuses an absent writable root rather than degrading quietly"),
        ("n05", "sandbox setup binds every root it is given before it enters the directory"),
        ("n06", "a contained spawn resolves the program against PATH before it starts"),
        ("n07", "the release tag is pushed alone or the workflow ships with no assets"),
        ("n08", "release notes are taken verbatim from the changelog by the workflow"),
        ("n09", "publishing happens last, after both merges and after the tag exists"),
    ];
    for (i, (k, v)) in notes.iter().enumerate() {
        // Padded, so nine notes cannot fit the block's share and something has
        // to be chosen. The padding is one token and shares nothing with any
        // goal, so it changes the arithmetic without changing the ranking.
        let value = format!("{v} {}", "z".repeat(240));
        store
            .memory_put(key, k, &value, 1, 1 + i as u32)
            .expect("the fixture writes must land");
    }
}

/// F1 — a turn about one subject is handed the notes about that subject, and the
/// notes it is not about are the ones elided.
///
/// The control is written out rather than described: the release notes are the
/// three newest in the store, so under 0.56.0's ordering they are exactly the
/// ones that survive. The test asserts they do not.
#[tokio::test]
async fn a_turn_about_one_subject_carries_the_notes_about_that_subject() {
    let dir = tempfile::tempdir().unwrap();
    let store = Store::memory().unwrap();
    let key = ws_key(dir.path());
    three_subjects(&store, &key);

    // The control, asserted rather than assumed: n07..n09 are the newest three,
    // so 0.56.0 would have kept them and dropped the parser notes.
    let listed = store.memory_list(&key).unwrap();
    let newest: Vec<&str> = listed.iter().rev().take(3).map(|e| e.key.as_str()).collect();
    assert_eq!(
        newest,
        vec!["n09", "n08", "n07"],
        "the fixture's premise: the release notes are the newest in the store"
    );

    let prompt = prompts(dir.path(), &store, "fix the parser", vec![vec![]])
        .await
        .remove(0);
    assert!(
        prompt.contains("note(s) elided to fit"),
        "the fixture must not fit, or nothing is being selected:\n{prompt}"
    );
    // Every note that survived is a parser note — asserted over what the block
    // rendered rather than by naming the ones expected to be there, because how
    // MANY fit is the ceiling's business and which SUBJECT fits is the release's.
    // Three notes tie on the signal here and the block holds fewer than three,
    // so an assertion listing all of them would be asserting the ceiling.
    let carried: Vec<String> = prompt
        .lines()
        .filter_map(|l| l.strip_prefix("- "))
        .filter_map(|l| l.split(':').next())
        .filter(|k| k.starts_with('n'))
        .map(str::to_string)
        .collect();
    assert!(
        !carried.is_empty(),
        "at least one note always survives:\n{prompt}"
    );
    for k in &carried {
        assert!(
            ["n01", "n02", "n03"].contains(&k.as_str()),
            "{k} is not a parser note and this turn is about the parser:\n{prompt}"
        );
    }
    for dropped in ["n07", "n08", "n09"] {
        assert!(
            !prompt.contains(&format!("- {dropped}:")),
            "{dropped} is the newest cohort and this turn is not about it — recency won:\n{prompt}"
        );
    }
}

/// F2 — a path the run has already read counts as a signal, so the second turn
/// of a run recalls differently from its first.
///
/// The goal deliberately names nothing in the store: with signals from the goal
/// alone the sandbox notes have no claim, and the newest cohort survives. It is
/// reading the file that moves them.
#[tokio::test]
async fn a_path_the_run_has_read_is_a_signal_the_next_turn_recalls_by() {
    let dir = tempfile::tempdir().unwrap();
    let store = Store::memory().unwrap();
    let key = ws_key(dir.path());
    three_subjects(&store, &key);
    std::fs::write(
        dir.path().join("sandbox.rs"),
        "// the file this run reads\n",
    )
    .unwrap();

    let read = ToolCall {
        name: "read_file".into(),
        arguments: json!({ "path": "sandbox.rs" }),
    };
    let seen = prompts(
        dir.path(),
        &store,
        "carry out the assignment",
        vec![vec![read], vec![]],
    )
    .await;
    assert_eq!(seen.len(), 2, "two turns, so the ledger differs between them");

    // Turn one: nothing has been read, the goal matches nothing, so the store's
    // own order decides and the newest cohort is carried.
    assert!(
        seen[0].contains("- n09:"),
        "with no signal at all the newest note is kept, as it was through 0.56.0:\n{}",
        seen[0]
    );
    // Turn two: the run has read `sandbox.rs`, and `sandbox` is a word three
    // notes share.
    for kept in ["n04", "n05"] {
        assert!(
            seen[1].contains(&format!("- {kept}:")),
            "the run has read sandbox.rs and {kept} is about the sandbox:\n{}",
            seen[1]
        );
    }
    assert!(
        !seen[1].contains("- n09:"),
        "the path the run touched must outrank the note that is merely newest:\n{}",
        seen[1]
    );
}

/// A ceiling that holds one note and not two, for the tie-break assertions —
/// where the whole claim is about which single entry survives.
fn tight(root: &Path, goal: &str) -> TaskContract {
    TaskContract::workspace(goal, root)
        .with_max_steps(2)
        .with_context_budget(ContextBudget {
            max_tokens: 600,
            share: 0.5,
        })
}

async fn tight_prompt(root: &Path, store: &Store, goal: &str) -> String {
    let seen = Seen(std::sync::Mutex::new(Vec::new()), vec![vec![]]);
    run_with(
        &tight(root, goal),
        &seen,
        store,
        &Policy::permissive(),
        &ApproveAll,
    )
    .await
    .expect("the run itself must not error");
    let out = seen.0.lock().unwrap().clone();
    out.into_iter().next().expect("one step happened")
}

/// F3 — draws break a signal tie, and the store's order breaks a draw tie.
///
/// The evidence is earned rather than inserted: `record_memory_recall` is the
/// crate's own, and a test that wrote its rows directly would be asserting
/// against a table no run had produced. Three runs happen while `s1` is the only
/// note in the store, so three runs carry it; `s2` is written afterwards, which
/// makes it both the newer entry and the one with nothing behind it. The clock
/// and the evidence therefore point opposite ways, which is the only arrangement
/// in which the assertion means anything.
#[tokio::test]
async fn draws_break_a_signal_tie_and_the_store_order_breaks_a_draw_tie() {
    let dir = tempfile::tempdir().unwrap();
    let store = Store::memory().unwrap();
    let key = ws_key(dir.path());

    // Both notes match a `sandbox` goal by exactly one word and share none of
    // their other vocabulary with it, so the first rank term cannot separate
    // them. Long enough that two of them cannot fit the tight ceiling.
    let s1 = format!("sandbox setup binds every root it is given, {}", "x".repeat(200));
    let s2 = format!("sandbox refuses an absent writable root, {}", "y".repeat(200));
    store.memory_put(&key, "s1", &s1, 1, 1).unwrap();
    for _ in 0..3 {
        tight_prompt(dir.path(), &store, "look at sandbox behaviour").await;
    }
    store.memory_put(&key, "s2", &s2, 1, 2).unwrap();

    let prompt = tight_prompt(dir.path(), &store, "look at sandbox behaviour").await;
    assert!(
        prompt.contains("- s1:"),
        "three runs have carried s1 and nothing has carried s2:\n{prompt}"
    );
    assert!(
        !prompt.contains("- s2:"),
        "s2 is newer, and being newer must not beat the evidence s1 earned:\n{prompt}"
    );

    // The tail: with no evidence anywhere and nothing in the goal to match, the
    // surviving entry is the store's own last one — 0.56.0's behaviour kept as
    // the tie-break rather than replaced.
    let quiet = Store::memory().unwrap();
    quiet.memory_put(&key, "s1", &s1, 1, 1).unwrap();
    quiet.memory_put(&key, "s2", &s2, 1, 2).unwrap();
    let prompt = tight_prompt(dir.path(), &quiet, "carry out the assignment").await;
    assert!(
        prompt.contains("- s2:") && !prompt.contains("- s1:"),
        "with nothing to rank by, the order the store returned decides:\n{prompt}"
    );
}

/// F5 — the printed block is the store's order, whatever the turn is about.
///
/// This is the caching claim, and it is asserted on bytes. Two runs over one
/// store with two goals that select **different** notes still print what they
/// kept in `(created_at, key)` order, and a store that fits its share prints
/// byte-identically under both goals — which is what makes the memory block a
/// repeatable prefix and 0.44.0's second cache breakpoint still reachable.
#[tokio::test]
async fn the_block_is_printed_in_the_stores_order_however_the_turn_moves() {
    let dir = tempfile::tempdir().unwrap();
    let store = Store::memory().unwrap();
    let key = ws_key(dir.path());
    three_subjects(&store, &key);

    let block = |prompt: &str| {
        let start = prompt.find("[memory]").expect("a block was rendered");
        let rest = &prompt[start..];
        let end = rest.find("\n\n").unwrap_or(rest.len());
        rest[..end].to_string()
    };
    let keys_in_order = |b: &str| {
        b.lines()
            .filter_map(|l| l.strip_prefix("- "))
            .filter_map(|l| l.split(':').next())
            .filter(|k| k.starts_with('n'))
            .map(str::to_string)
            .collect::<Vec<_>>()
    };

    let parser = block(&prompts(dir.path(), &store, "fix the parser", vec![vec![]]).await[0]);
    let release = block(&prompts(dir.path(), &store, "cut the release", vec![vec![]]).await[0]);
    assert_ne!(
        keys_in_order(&parser),
        keys_in_order(&release),
        "the two goals must select different notes, or this test proves nothing"
    );
    for b in [&parser, &release] {
        let printed = keys_in_order(b);
        let mut sorted = printed.clone();
        sorted.sort();
        assert_eq!(
            printed, sorted,
            "the block is printed in the store's order, never in the order the fit chose:\n{b}"
        );
    }

    // The half that carries the caching claim: when everything fits, the block
    // does not move at all between two turns about different things.
    let small = Store::memory().unwrap();
    small.memory_put(&key, "a01", "the parser rejects a trailing comma", 1, 1).unwrap();
    small.memory_put(&key, "a02", "the release tag is pushed alone", 1, 2).unwrap();
    let one = block(&prompts(dir.path(), &small, "fix the parser", vec![vec![]]).await[0]);
    let two = block(&prompts(dir.path(), &small, "cut the release", vec![vec![]]).await[0]);
    assert_eq!(
        one, two,
        "a store inside its share renders byte-identically whatever the turn is about"
    );
    assert!(
        !one.contains("elided to fit"),
        "the fixture for this half must fit, or it is asserting the other regime"
    );
}

/// F6 — the same store and the same turn select the same notes twice.
///
/// The ordering is a pure function of the store and the turn, which is what lets
/// a replayed run recall what the run it replays did. Asserted by running the
/// same turn twice over one store and comparing the whole prompt, then by
/// writing one note and asserting the new selection is itself repeatable rather
/// than merely different.
#[tokio::test]
async fn the_same_store_and_the_same_turn_select_the_same_notes_twice() {
    let dir = tempfile::tempdir().unwrap();
    let store = Store::memory().unwrap();
    let key = ws_key(dir.path());
    three_subjects(&store, &key);

    let once = prompts(dir.path(), &store, "fix the parser", vec![vec![]]).await;
    let twice = prompts(dir.path(), &store, "fix the parser", vec![vec![]]).await;
    assert_eq!(
        once[0], twice[0],
        "two identical turns over one store must assemble one prompt"
    );

    store
        .memory_put(&key, "n10", "the parser keeps a token's own span", 1, 10)
        .unwrap();
    let after = prompts(dir.path(), &store, "fix the parser", vec![vec![]]).await;
    let again = prompts(dir.path(), &store, "fix the parser", vec![vec![]]).await;
    assert_ne!(
        once[0], after[0],
        "a note that matches the turn must change what is carried, or the first \
         assertion holds for the wrong reason"
    );
    assert_eq!(
        after[0], again[0],
        "the new selection is a function of the new store, not of anything else"
    );
}
